### ISSUE TITLE
Error trying to dispatch two connections

### ISSUE THREAD

**Issue by kharysiri** [Morhaus/dispatch-proxy#44]
Hi! i have two connections and when i try to use jdownloader or any torrent client throws me this errors:
(note: using socks or http option, both of them doesnt work, any ideas?)

C:\Windows\system32>dispatch start
SOCKS server started on localhost:1080
Dispatching to addresses 10.0.0.99@1, 10.0.0.6@1
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)

C:\Windows\system32>dispatch start --http
HTTP server started on localhost:8080
Dispatching to addresses 10.0.0.99@1, 10.0.0.6@1
^C¿Desea terminar el trabajo por lotes (S/N)? s

C:\Windows\system32>dispatch start
SOCKS server started on localhost:1080
Dispatching to addresses 10.0.0.99@1, 10.0.0.6@1
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)

C:\Windows\system32>dispatch start --http
HTTP server started on localhost:8080
Dispatching to addresses 10.0.0.99@1, 10.0.0.6@1
^C¿Desea terminar el trabajo por lotes (S/N)? s

C:\Windows\system32>dispatch start
SOCKS server started on localhost:1080
Dispatching to addresses 10.0.0.99@1, 10.0.0.6@1
C:\Users\Server\AppData\Roaming\npm\node_modules\dispatch-proxy\node_modules\soc
ks-handler\lib\socks4\index.js:23
        return request.call(this, chunk);
                       ^
TypeError: undefined is not a function
    at Stream.<anonymous> (C:\Users\Server\AppData\Roaming\npm\node_modules\disp
atch-proxy\node_modules\socks-handler\lib\socks4\index.js:23:24)
    at Stream.stream.write (C:\Users\Server\AppData\Roaming\npm\node_modules\dis
patch-proxy\node_modules\socks-handler\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

Ty for your time!

**Comment by SMed79** [comment]
Try running it on an other port "`dispatch start --http -p 1025`" (for port 1025).
source: https://github.com/Morhaus/dispatch-proxy/issues/19#issuecomment-30616552
