### ISSUE TITLE
client request error

### ISSUE THREAD

**Issue by martingg88** [Morhaus/dispatch-proxy#49]
any idea what cause following issue?

dispatch start --http -p 7000
HTTP server started on localhost:7000
Dispatching to addresses 10.3.150.3@1, 192.168.1.3@1
     error [068db1] clientRequest
           Error: connect EADDRNOTAVAIL
               at exports._errnoException (util.js:746:11)
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
     error [90108d] clientRequest
           Error: connect EADDRNOTAVAIL
               at exports._errnoException (util.js:746:11)
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

**Comment by Morhaus** [comment]
Does the proxy not work at all, or only on certain requests? One of the interface might not be functioning correctly.

**Comment by martingg88** [comment]
it may be my mistake. forget about this. does this support partial transferring with status code 206?

**Comment by leandroong** [comment]
I'm having same issues. Yes, I'm running it at 1 interface only (wifi). So far, no issue in surfing.

**Comment by leandroong** [comment]
Solution: Since we are not coder and not interested in error displays, i recommend to do this
dispatch  start -http > nul
