### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by leojohnpc** [Morhaus/dispatch-proxy#55]
Hi, Good Day! Please tell me how  to fix this errors : 
C:\Windows\system32>dispatch start
SOCKS server started on localhost:1080
Dispatching to addresses 192.168.0.15@1, 192.168.254.9@1
     error [f20b1c] clientConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [d71585] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [11dd7a] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [c85d9d] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [22dffc] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [ee988b] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [ec4299] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [68daef] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [5a5d52] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [ce37fe] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [3766c4] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [14e6a7] clientConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [a0b26a] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [156701] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [f8c2f2] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [651e33] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [7b068e] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
     error [373fde] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:746:11)
               at TCP.onread (net.js:559:26)
I tried to change the port but the errors still appear.

**Comment by leandroong** [comment]
Suppress errors from displaying by using this command, "dispatch start > nul"

**Comment by leojohnpc** [comment]
thanks for the reply! Is it ok to ignore this errors?
