### ISSUE TITLE
Timedout when trying to dispatch to second interface

### ISSUE THREAD

**Issue by doylefermi** [Morhaus/dispatch-proxy#68]
#Tried on 2 wifi interfaces.

Download manager: **aria2**

On using socks, displays unsupported socks version 71

![image](https://cloud.githubusercontent.com/assets/8755940/21494543/4e5c4ece-cc38-11e6-95c8-770356790425.png)

`HTTP server started on localhost:8080
Dispatching to addresses 192.168.1.100@1, 192.168.2.8@1
   request [c75a0c] http://dl2.mihanpix.com/Film/2016/Kung.Fu.Panda.3.2016.720p.BRrip.Exclusive.Farsi.Dubbed.(2Dooble).mkv
  dispatch [c75a0c] 192.168.1.100
       end [c75a0c] clientRequest
  response [c75a0c] 200
   request [8996a7] http://dl2.mihanpix.com/Film/2016/Kung.Fu.Panda.3.2016.720p.BRrip.Exclusive.Farsi.Dubbed.(2Dooble).mkv
  dispatch [8996a7] 192.168.2.8
       end [8996a7] clientRequest
   request [7edd2c] http://dl2.mihanpix.com/Film/2016/Kung.Fu.Panda.3.2016.720p.BRrip.Exclusive.Farsi.Dubbed.(2Dooble).mkv
  dispatch [7edd2c] 192.168.1.100
       end [7edd2c] clientRequest
  response [7edd2c] 200
   request [32ac3c] http://dl2.mihanpix.com/Film/2016/Kammatti.Paadam.2016.DVDRip.x264.mkv
  dispatch [32ac3c] 192.168.2.8
       end [32ac3c] clientRequest
     error [8996a7] clientRequest
           Error: connect ETIMEDOUT 104.31.64.79:80
               at Object.exports._errnoException (util.js:1022:11)
               at exports._exceptionWithHostPort (util.js:1045:20)
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
   request [94f13c] http://dl2.mihanpix.com/Film/2016/Kammatti.Paadam.2016.DVDRip.x264.mkv
  dispatch [94f13c] 192.168.1.100
       end [94f13c] clientRequest
  response [94f13c] 200
     error [32ac3c] clientRequest
           Error: connect ETIMEDOUT 104.31.65.79:80
               at Object.exports._errnoException (util.js:1022:11)
               at exports._exceptionWithHostPort (util.js:1045:20)
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
^C
`

**Comment by Morhaus** [comment]
Hey,

When using the SOCKS server, the `Unsupported SOCKS version 71` message means that whatever client is using the proxy expects a HTTP or HTTPS proxy, so you should use that instead.

From the error log, it looks like the interface at 192.168.2.8 is not responding properly. Are you sure it's correctly connected to the internet?

You can try each interface independently via `dispatch start --http --debug 192.168.1.100@1` and  `dispatch start --http --debug 192.168.2.8@1`. If the second one doesn't work at all, then that means that something is wrong with the interface `wlp0s20f0u1`.

**Comment by doylefermi** [comment]
Hi,

Tried, the interfaces work individually. They are connected to different AP's as well.

I have uploaded a [video](https://ptpb.pw/jDBk.ogv) that shows the issue. Couldnt get error logs.

Thanks.
