### ISSUE TITLE
error [e4f62e] clientConnection Error: read ECONNRESET at exports._errnoException (util.js:1036:11) at TCP.onread (net.js:564:26) ?

### ISSUE THREAD

**Issue by minanagehsalalma** [Morhaus/dispatch-proxy#76]
I am using node.js dispatch to merge two Wifi connections but while downloading with the Internet Download Manager the node.js dispatch show the following error:
error [e4f62e] clientConnection Error: read ECONNRESET at exports._errnoException (util.js:1036:11) at TCP.onread (net.js:564:26)
After a while of using it the speed decreasing or the node.js dispatch process suddenly crashes. So is there a way to fix this ?
![image](https://user-images.githubusercontent.com/20546638/30605287-6760853c-9d22-11e7-8434-e68872583efa.png)
![image](https://user-images.githubusercontent.com/20546638/30605300-6dfe68d2-9d22-11e7-92e2-0707a006c46f.png)

and if i used there internet sources it doesn't work ..

**Comment by minanagehsalalma** [comment]
@Morhaus  thanks for nothing
